import { scaleVariants } from "@acerohernan/ui-kit";
import { Button as PancakeButton } from "@pancakeswap/uikit";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Web application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Web</h1>
        <PancakeButton>Hello</PancakeButton>
        <pre>{JSON.stringify(scaleVariants)}</pre>
      </main>
    </>
  );
}
